version: '3'
services:
  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.3.1
#    environment:
#      - ALERTMANAGER_URL=http://localhost:9093
#      - BOLT_PATH=/data/bot.db
#      - STORE=bolt
#      - TELEGRAM_ADMIN='364008202'
#      - TELEGRAM_TOKEN=781076437:AAFV9zWpKMr7AJ4jXh_9ISvmMXq8QxOG1r4
#      - TEMPLATE_PATHS=/templates/default.tmpl
    command:
      - '--alertmanager.url=http://10.35.1.200:9093'
      - '--bolt.path=/data/bot.db'
      - '--store=bolt'
      - '--telegram.admin=364008202'
      - '--telegram.token=781076437:AAFV9zWpKMr7AJ4jXh_9ISvmMXq8QxOG1r4'
      - '--listen.addr=0.0.0.0:8080'
    ports:
      - '9095:8080'
    volumes:
        - /srv/monitoring/alertmanager-bot:/data