version: '2.1'

volumes:
#    prometheus_data: {}
    grafana_data: {}
services:
    prometheus:
        image: prom/prometheus
        privileged: true
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./host.rules.yml:/etc/prometheus/host.rules.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'

        ports:
            - '9090:9090'

    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'

    alertmanager:
        image: prom/alertmanager
        privileged: true
        volumes:
             - ./alertmanager.yml:/alertmanager.yml
        command:
            - '--config.file=/alertmanager.yml'
        ports:
            - '9093:9093'
    alertmanager-bot:
        image: metalmatze/alertmanager-bot:0.3.1
        command:
            - '--alertmanager.url=http://alertmanager:9093'
            - '--bolt.path=/data/bot.db'
            - '--store=bolt'
            - '--telegram.admin=364008202'
            - '--telegram.token=781076437:AAFV9zWpKMr7AJ4jXh_9ISvmMXq8QxOG1r4'
            - '--listen.addr=0.0.0.0:8080'
        volumes:
            - /srv/monitoring/alertmanager-bot:/data
    
    grafana:
        image: grafana/grafana:5.4.2
        container_name: grafana
        user: root
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/datasources:/etc/grafana/datasources
          - ./grafana/dashboards:/etc/grafana/dashboards
          - ./grafana/setup.sh:/setup.sh
        
        entrypoint: /setup.sh
        environment:
          - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
          - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
          - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        ports:
          - '3000:3000'