scrape_configs:
  - job_name: rabbitmq
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['e2k-kub02:15672']
  
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - "host.rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'